services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: buru
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
