"""patch entries table to have username column and no optional name column

Revision ID: 04d2707d23f0
Revises: 368a774756c2
Create Date: 2026-05-25 16:11:18.689208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04d2707d23f0"
down_revision: Union[str, Sequence[str], None] = "368a774756c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("username", sa.String(), nullable=True))
    op.drop_column("entries", "optional_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column("optional_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("entries", "username")
    # ### end Alembic commands ###
