"""unique platform-username

Revision ID: 1f0550f1384e
Revises: b38e90a700e4
Create Date: 2026-05-25 16:28:53.960326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0550f1384e'
down_revision: Union[str, Sequence[str], None] = 'b38e90a700e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entries', ['user_id', 'platform', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='unique')
    # ### end Alembic commands ###
