"""more fields for entries

Revision ID: 8064e6fae80d
Revises: d0b68167ceff
Create Date: 2026-05-30 11:01:36.635496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8064e6fae80d'
down_revision: Union[str, Sequence[str], None] = 'd0b68167ceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('url', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('modified_at', sa.String(), nullable=False))
    op.add_column('entries', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'tag')
    op.drop_column('entries', 'modified_at')
    op.drop_column('entries', 'url')
    # ### end Alembic commands ###
