"""iv for entries

Revision ID: d0b68167ceff
Revises: 1f0550f1384e
Create Date: 2026-05-29 19:09:04.738196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b68167ceff'
down_revision: Union[str, Sequence[str], None] = '1f0550f1384e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('iv', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'iv')
    # ### end Alembic commands ###
